Dados: https://www.kaggle.com/datasets/namespaiva/base-varejo/data

# 1. Importar bibiliotecas/pacotes

In [ ]:
import os
import csv
import pandas as pd
from google.colab import drive, files

# 2. Criar lista vazia

In [ ]:
tabela_dados = []

# 3. Abrir e ler o arquivo

In [ ]:
with open('/content/drive/MyDrive/Collab dados /Base Varejo.csv','r', encoding='utf-8') as arquivo:
    leitor = csv.DictReader(arquivo, delimiter=';')
    for linha in leitor:
        tabela_dados.append(linha)

In [ ]:
print (tabela_dados[5])

{'DATA': '01/02/2019', 'CO_ID': '1000', 'CL_ID': '534', 'CL_GENERO': 'M', 'CL_EC': '4', 'CL_FHL': '1', 'CL_SEG': 'C', 'PR_ID': '187', 'PR_CAT': 'HIGIENE', 'PR_NOME': 'HASTES FLEXIVEIS', '': ''}

# 4. Transformar em Dataframe

In [ ]:
df = pd.DataFrame(tabela_dados)

In [ ]:
df

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,
...,...,...,...,...,...,...,...,...,...,...,...
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA,
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO,

# 5. Verificar, Manipular e Limpar dados

In [ ]:
df.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 11 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATA       830000 non-null  object
 1   CO_ID      830000 non-null  object
 2   CL_ID      830000 non-null  object
 3   CL_GENERO  830000 non-null  object
 4   CL_EC      830000 non-null  object
 5   CL_FHL     830000 non-null  object
 6   CL_SEG     830000 non-null  object
 7   PR_ID      830000 non-null  object
 8   PR_CAT     830000 non-null  object
 9   PR_NOME    830000 non-null  object
 10             830000 non-null  object
dtypes: object(11)
memory usage: 69.7+ MB

In [ ]:
df.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,

In [ ]:
df.tail()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA,
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO,

In [ ]:
df.describe()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,
count,830000,830000,830000,830000,830000,830000,830000,830000,830000,830000,830000
unique,333,18471,1000,2,5,5,3,229,7,118,1
top,21/08/2020,919626,822,F,3,0,B,93,ALIMENTOS,PRESUNTO COZIDO,
freq,4641,89,1777,432576,213742,435501,530163,3773,434767,14381,830000

In [ ]:
# transformar as colunas (objetos) em inteiros (int)
from numpy import info

colunas_inteiras = ['CO_ID', 'CL_ID', 'CL_EC', 'CL_FHL', 'PR_ID']
for coluna in colunas_inteiras:
    df[coluna] = pd.to_numeric(df[coluna], errors='coerce')
    print("Código executado do zero!")

    print("-" * 30)

Código executado do zero!
------------------------------
Código executado do zero!
------------------------------
Código executado do zero!
------------------------------
Código executado do zero!
------------------------------
Código executado do zero!
------------------------------

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 11 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATA       830000 non-null  object
 1   CO_ID      830000 non-null  int64
 2   CL_ID      830000 non-null  int64
 3   CL_GENERO  830000 non-null  object
 4   CL_EC      830000 non-null  int64
 5   CL_FHL     830000 non-null  int64
 6   CL_SEG     830000 non-null  object
 7   PR_ID      830000 non-null  int64
 8   PR_CAT     830000 non-null  object
 9   PR_NOME    830000 non-null  object
 10             830000 non-null  object
dtypes: int64(5), object(6)
memory usage: 69.7+ MB

In [ ]:
df.columns = df.columns.str.strip().str.upper()

In [ ]:
df['DATA'] = df['DATA'].astype(str).str.strip()

In [ ]:
# valores ausentes

df.isna()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
829995,False,False,False,False,False,False,False,False,False,False,False
829996,False,False,False,False,False,False,False,False,False,False,False
829997,False,False,False,False,False,False,False,False,False,False,False
829998,False,False,False,False,False,False,False,False,False,False,False
829999,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
# Identificar duplicatas
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
829995     True
829996     True
829997     True
829998    False
829999    False
Length: 830000, dtype: bool

In [ ]:
# Visualizar
df[df.duplicated()]

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,
40,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,
46,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,
49,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO,
50,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,
...,...,...,...,...,...,...,...,...,...,...,...
829989,19/08/2022,919822,155,F,2,0,B,34,ALIMENTOS,KETCHUP,
829992,19/08/2022,919822,155,F,2,0,B,30,ALIMENTOS,FILE DE PEIXE,
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,

In [ ]:
(df.duplicated(subset=['DATA','CO_ID', 'CL_ID', 'PR_ID', 'PR_CAT']).sum())

np.int64(96553)

# 7. Criar cópia para análise

In [ ]:
df_copy = df.copy()

In [ ]:
# mapear estado Civil
mapeamento_ec = {1: 'Casado/União Estável', 2: 'Divorciado', 3: 'Separado', 4: 'Solteiro', 5: 'Viúvo'}
df_copy['CL_EC_TEXTO'] = df_copy['CL_EC'].map(mapeamento_ec)

In [ ]:
df_copy

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,,CL_EC_TEXTO
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,,Solteiro
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,,Solteiro
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,,Solteiro
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,,Solteiro
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,,Solteiro
...,...,...,...,...,...,...,...,...,...,...,...,...
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,,Divorciado
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,,Divorciado
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,,Divorciado
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA,,Divorciado
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO,,Divorciado

In [ ]:
# verificar estado civil
print("QUANTIDADE DE REGISTROS POR ESTADO CIVIL:")
(df_copy['CL_EC_TEXTO'].value_counts())

QUANTIDADE DE REGISTROS POR ESTADO CIVIL:

CL_EC_TEXTO
Separado                213742
Solteiro                202618
Divorciado              194990
Casado/União Estável    194873
Viúvo                    23777
Name: count, dtype: int64

In [ ]:
 # mostra clientes com IDs diferentes
clientes_unicos = df_copy.drop_duplicates(subset=['CL_ID'])

In [ ]:
clientes_unicos

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,,CL_EC_TEXTO
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,,Solteiro
52,01/02/2019,1040,279,M,1,2,B,38,ALIMENTOS,LEITE CONDENSADO,,Casado/União Estável
67,01/02/2019,1078,290,F,1,0,B,145,PET,RACAO UMIDA PARA GATOS,,Casado/União Estável
149,01/02/2019,1082,323,M,1,3,B,69,BEBIDAS,REFRIGERANTE LIMaO,,Casado/União Estável
220,01/02/2019,1103,957,M,2,3,B,15,ALIMENTOS,BATATA DOCE,,Divorciado
...,...,...,...,...,...,...,...,...,...,...,...,...
235713,03/04/2020,261636,557,F,2,0,A,176,LIMPEZA,LIMPA VIDROS,,Divorciado
236630,03/04/2020,262515,92,M,4,1,B,2,ACESSORIOS,MORDEDOR,,Solteiro
267652,14/04/2020,296960,321,M,2,0,B,44,ALIMENTOS,MAMAO,,Divorciado
271451,19/04/2020,301608,787,F,3,0,A,167,ALIMENTOS,MANGA,,Separado
355092,21/09/2020,391326,184,M,1,3,B,17,ALIMENTOS,BISCOITO,,Casado/União Estável

In [ ]:
# analisar gêneros

print("QUANTIDADE DE CLIENTES CADASTRADOS POR GÊNERO:")
(clientes_unicos['CL_GENERO'].value_counts())

QUANTIDADE DE CLIENTES CADASTRADOS POR GÊNERO:

CL_GENERO
F    519
M    481
Name: count, dtype: int64

In [ ]:
# agrupamento de gênero e total de compras
compras_genero = df.groupby('CL_GENERO').size().reset_index(name='TOTAL_COMPRAS')
(compras_genero)

  CL_GENERO  TOTAL_COMPRAS
0         F         432576
1         M         397424

In [ ]:
compras_unicas = df.drop_duplicates(subset=['CO_ID'])
total_de_compras = len(compras_unicas)

In [ ]:
# Compras (total) por gênero
resultado = compras_unicas.groupby('CL_GENERO').size().reset_index(name='TOTAL_COMPRAS')
(resultado)

  CL_GENERO  TOTAL_COMPRAS
0         F           9615
1         M           8856

In [ ]:
# total de filhos por gênero

total_filhos_genero = compras_unicas.groupby('CL_GENERO')['CL_FHL'].sum().reset_index(name='TOTAL_FILHOS')
(total_filhos_genero)

  CL_GENERO  TOTAL_FILHOS
0         F         10383
1         M         10734

In [ ]:
# média de filhos
filhos_por_genero = compras_unicas.groupby('CL_GENERO')['CL_FHL'].mean().reset_index(name='MEDIA_FILHOS')
(filhos_por_genero)

  CL_GENERO  MEDIA_FILHOS
0         F      1.079875
1         M      1.212060

In [ ]:
# Agrupamenteo de gênero e desvio padrão da coluna de filhos
desvio_por_genero = clientes_unicos.groupby('CL_GENERO')['CL_FHL'].std().reset_index(name='DESVIO_FILHOS')
(desvio_por_genero)

  CL_GENERO  DESVIO_FILHOS
0         F       1.364611
1         M       1.463180

In [ ]:
# Categoria do produto mais vendida

categoria_vendas = df.groupby('PR_CAT').size().reset_index(name='QUANTIDADE_VENDIDA')
(categoria_vendas)

       PR_CAT  QUANTIDADE_VENDIDA
0        #N/D                3650
1  ACESSORIOS               14557
2   ALIMENTOS              434767
3     BEBIDAS               43299
4     HIGIENE              155574
5     LIMPEZA              145754
6         PET               32399

In [ ]:
 # do maior para o menor
categoria_vendas = categoria_vendas.sort_values(by='QUANTIDADE_VENDIDA', ascending=False)
(categoria_vendas)

       PR_CAT  QUANTIDADE_VENDIDA
2   ALIMENTOS              434767
4     HIGIENE              155574
5     LIMPEZA              145754
3     BEBIDAS               43299
6         PET               32399
1  ACESSORIOS               14557
0        #N/D                3650

In [ ]:
classe_compras = compras_unicas.groupby('CL_SEG').size().reset_index(name='TOTAL_COMPRAS')
(classe_compras)

  CL_SEG  TOTAL_COMPRAS
0      A           1492
1      B          11843
2      C           5136

# Conclusões:

1. Embora o cadastro de clientes possa ser equilibrado, o gênero feminino domina o volume real de notas fiscais;
2. Alimentação ficou em primeiro lugar em compras pelos clientes, seguindo de produtos de higiene e limpeza, em terceiro lugar; e grandes de estoque/abastecimento, e não em compras rápidas de oportunidade.
3. A concentração por Segmento Social: está na Classe B, que acumula 11.843 compras,seguido pela Classe C e, por último, pela Classe A.
4. Sobre o perfil familiar: O cálculo do desvio padrão revelou que o número de filhos varia mais entre os homens do que entre as mulheres.
5. Na verificação de itens duplicados, o produto Ketchup apareceu duas vezes([vide célula](https://colab.research.google.com/drive/1pHxLqIm6ZkcizA24ypH9eB6-LhUws4X6#scrollTo=AX65r4d0RFOm&line=2&uniqifier=1) mas não foi eliminado porque apresentou dois PR_ID distintos, que pode indicar que o cliente comprou dois tipos de mesmo nom (Ketchup) e, por ter sido registrada uma identificação diferente (SKU) - pode ser uma indicação de diferente produto devido ao tamanho da embalagem, qualidade ou marca que diferenciam um do outro com mesmo nome.